// <auto-generated />
using System;
using BT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BT.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BT.Domain.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Province")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("BT.Domain.Domain.Avatar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Filename")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("longblob");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Avatar");
                });

            modelBuilder.Entity("BT.Domain.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f70d917-509b-4203-a9a7-a195f01c1ca1"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(3354),
                            Name = "Basketball",
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(3843)
                        },
                        new
                        {
                            Id = new Guid("51771ba3-80f5-45e2-9bda-6d9cc3b939f6"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4314),
                            Name = "Football",
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4349)
                        },
                        new
                        {
                            Id = new Guid("619b475a-81d4-4c55-8e48-2349bac9a37f"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4364),
                            Name = "Hokey",
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4365)
                        },
                        new
                        {
                            Id = new Guid("f16d8ed3-d085-4eaf-8071-f71332d49f80"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4381),
                            Name = "Running",
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4382)
                        },
                        new
                        {
                            Id = new Guid("e5db81e8-61b2-4323-b32a-4afe91e890d4"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4386),
                            Name = "Ski",
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(4387)
                        });
                });

            modelBuilder.Entity("BT.Domain.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BT.Domain.Domain.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<Guid>("MeetingOrganizerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MeetingOrganizerId");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ccbb1ca-0a0b-4ee2-a66d-f1c1411a23d2"),
                            CategoryId = new Guid("1f70d917-509b-4203-a9a7-a195f01c1ca1"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(181),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 453, DateTimeKind.Utc).AddTicks(5459),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 12,
                            MeetingOrganizerId = new Guid("b23033ad-a3b6-41fd-9273-0a8add33990a"),
                            Name = "Find people to play basketball",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(559)
                        },
                        new
                        {
                            Id = new Guid("0115c83b-7c52-4944-86f1-cc84c16dc258"),
                            CategoryId = new Guid("1f70d917-509b-4203-a9a7-a195f01c1ca1"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(1952),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(1747),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 6,
                            MeetingOrganizerId = new Guid("10fa020f-0948-4057-b442-70c6f336e273"),
                            Name = "Find 6 guys to our basketball team",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(1967)
                        },
                        new
                        {
                            Id = new Guid("eccc001f-55c0-4b88-b77a-3bf593a420c2"),
                            CategoryId = new Guid("51771ba3-80f5-45e2-9bda-6d9cc3b939f6"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2008),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2003),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 21,
                            MeetingOrganizerId = new Guid("6fe8e178-20a8-4be7-92b0-70db4e6d39c4"),
                            Name = "Find friends to casual play",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2010)
                        },
                        new
                        {
                            Id = new Guid("de2f774f-9d26-4886-8499-9fa4b7620dbc"),
                            CategoryId = new Guid("51771ba3-80f5-45e2-9bda-6d9cc3b939f6"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2029),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2012),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 3,
                            MeetingOrganizerId = new Guid("b23033ad-a3b6-41fd-9273-0a8add33990a"),
                            Name = "Footboll tomorrow",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2031)
                        },
                        new
                        {
                            Id = new Guid("90418db2-0429-41c8-95b1-88ba140db598"),
                            CategoryId = new Guid("619b475a-81d4-4c55-8e48-2349bac9a37f"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2036),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2032),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 6,
                            MeetingOrganizerId = new Guid("10fa020f-0948-4057-b442-70c6f336e273"),
                            Name = "Find team to game",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2037)
                        },
                        new
                        {
                            Id = new Guid("a226c49f-ae4e-4170-8302-77aebedfa022"),
                            CategoryId = new Guid("619b475a-81d4-4c55-8e48-2349bac9a37f"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2042),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2039),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 12,
                            MeetingOrganizerId = new Guid("6fe8e178-20a8-4be7-92b0-70db4e6d39c4"),
                            Name = "ICE IS COLD. THIS WEEKEND",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2043)
                        },
                        new
                        {
                            Id = new Guid("1d8fab4f-2a9b-47d2-ae00-9c09de237f83"),
                            CategoryId = new Guid("f16d8ed3-d085-4eaf-8071-f71332d49f80"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2058),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2045),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 2,
                            MeetingOrganizerId = new Guid("10fa020f-0948-4057-b442-70c6f336e273"),
                            Name = "Find somebody to running together",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2059)
                        },
                        new
                        {
                            Id = new Guid("efd637ec-4458-4154-9b49-e3b182543950"),
                            CategoryId = new Guid("f16d8ed3-d085-4eaf-8071-f71332d49f80"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2064),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2061),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 100,
                            MeetingOrganizerId = new Guid("b23033ad-a3b6-41fd-9273-0a8add33990a"),
                            Name = "Marathon",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2065)
                        },
                        new
                        {
                            Id = new Guid("d41c6422-33b1-4ab9-b9b5-c43a89ca4421"),
                            CategoryId = new Guid("e5db81e8-61b2-4323-b32a-4afe91e890d4"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2070),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2067),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 1,
                            MeetingOrganizerId = new Guid("b23033ad-a3b6-41fd-9273-0a8add33990a"),
                            Name = "Ski in Tatry",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2072)
                        },
                        new
                        {
                            Id = new Guid("56b39e65-217a-42a2-80d4-86686beaeb00"),
                            CategoryId = new Guid("e5db81e8-61b2-4323-b32a-4afe91e890d4"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2076),
                            Date = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2073),
                            Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Duis semper purus venenatis diam pulvinar, vitae porttitor sem ornare. Vivamus interdum viverra
            mattis. Proin sodales neque massa, et pulvinar lectus accumsan non. Mauris blandit, mi vel 
            facilisis posuere, quam mauris rutrum est, nec auctor lorem libero pretium elit. Nunc hendrerit 
            euismod urna, eget viverra est condimentum a. Nunc mattis porta cursus. Nulla finibus lobortis est 
            a viverra. Duis consequat neque eget ligula sodales sodales. Curabitur scelerisque ac nulla eget hendrerit. 
            Duis nec nunc id eros lacinia ullamcorper. Cras porttitor, sapien vulputate fermentum sagittis, nibh dolor 
            aliquam velit, a sodales tortor lectus sit amet quam. Phasellus tempor sollicitudin porttitor. In eu sapien 
            a ipsum sollicitudin malesuada quis a elit. Integer sit amet fringilla dui. In viverra vel velit nec posuere. 
            Proin sed nisi tempus, placerat nisi at, imperdiet libero. Suspendisse sollicitudin risus ante, eget rutrum 
            dui sagittis et. Maecenas commodo sagittis ligula, vitae fringilla ligula mollis sit amet. In hac habitasse 
            platea dictumst. Suspendisse vehicula nulla luctus, mollis risus id, consectetur libero. Integer interdum 
            varius justo. Nam finibus fringilla leo eu lacinia.",
                            MaxParticipants = 12,
                            MeetingOrganizerId = new Guid("6fe8e178-20a8-4be7-92b0-70db4e6d39c4"),
                            Name = "Ski next winter group",
                            ParticipantCount = 0,
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 454, DateTimeKind.Utc).AddTicks(2078)
                        });
                });

            modelBuilder.Entity("BT.Domain.Domain.MeetingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Filename")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingImages");
                });

            modelBuilder.Entity("BT.Domain.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("BT.Domain.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Firstname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Lastname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b23033ad-a3b6-41fd-9273-0a8add33990a"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(2696),
                            Email = "admin@bt.com",
                            Firstname = "Aleksaner",
                            Lastname = "Ciechanowski",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(3403)
                        },
                        new
                        {
                            Id = new Guid("6fe8e178-20a8-4be7-92b0-70db4e6d39c4"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4073),
                            Email = "admin1@bt.com",
                            Firstname = "Donald",
                            Lastname = "Lukaszenka",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4089)
                        },
                        new
                        {
                            Id = new Guid("10fa020f-0948-4057-b442-70c6f336e273"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4109),
                            Email = "admin2@bt.com",
                            Firstname = "Andrzej",
                            Lastname = "Kaczynski",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4111)
                        },
                        new
                        {
                            Id = new Guid("b2131cb2-ec73-470d-bba5-0a350c3c64b4"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4406),
                            Email = "btmail@bt.com",
                            Firstname = "Jack",
                            Lastname = "Nowak",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4407)
                        },
                        new
                        {
                            Id = new Guid("05ac4842-73f2-47f9-8bc5-ddc2baf26e21"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4411),
                            Email = "btmail1@bt.com",
                            Firstname = "George",
                            Lastname = "Bush",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4412)
                        },
                        new
                        {
                            Id = new Guid("77525bc2-3b61-4e1f-ac07-5ad1a8d9fbf1"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4415),
                            Email = "btmail2@bt.com",
                            Firstname = "Alina",
                            Lastname = "Ivanov",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4416)
                        },
                        new
                        {
                            Id = new Guid("1022fd8f-28fd-46c4-88d4-00924f4c99b4"),
                            CreatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4420),
                            Email = "btmail3@bt.com",
                            Firstname = "Ksenya",
                            Lastname = "Barbie",
                            Password = "123456",
                            Salt = new byte[] { 98, 116, 45, 115, 97, 108, 116 },
                            UpdatedAt = new DateTime(2020, 10, 6, 21, 58, 16, 451, DateTimeKind.Utc).AddTicks(4421)
                        });
                });

            modelBuilder.Entity("BT.Domain.Domain.UserMeeting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "MeetingId");

                    b.HasIndex("MeetingId");

                    b.ToTable("UserMeeting");
                });

            modelBuilder.Entity("BT.Domain.Domain.Address", b =>
                {
                    b.HasOne("BT.Domain.Domain.Meeting", "Meeting")
                        .WithOne("Address")
                        .HasForeignKey("BT.Domain.Domain.Address", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Domain.Avatar", b =>
                {
                    b.HasOne("BT.Domain.Domain.User", "User")
                        .WithOne("Avatar")
                        .HasForeignKey("BT.Domain.Domain.Avatar", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Domain.Comment", b =>
                {
                    b.HasOne("BT.Domain.Domain.Meeting", "Meeting")
                        .WithMany("Comments")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BT.Domain.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Domain.Meeting", b =>
                {
                    b.HasOne("BT.Domain.Domain.Category", "Category")
                        .WithMany("Meetings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BT.Domain.Domain.User", "MeetingOrganizer")
                        .WithMany("OrganizedMeetings")
                        .HasForeignKey("MeetingOrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Domain.MeetingImage", b =>
                {
                    b.HasOne("BT.Domain.Domain.Meeting", "Meeting")
                        .WithMany("Images")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Domain.RefreshToken", b =>
                {
                    b.HasOne("BT.Domain.Domain.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("BT.Domain.Domain.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Domain.UserMeeting", b =>
                {
                    b.HasOne("BT.Domain.Domain.Meeting", "Meeting")
                        .WithMany("Participants")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BT.Domain.Domain.User", "User")
                        .WithMany("EnrolledMeetings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
