name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet ../BT.Api restore
    - name: Build
      run: dotnet build ../BT.Api --configuration Release --no-restore
    - name: Test
      run: dotnet test ../BT.Test --no-restore --verbosity normal
